
SOURCES += \
    $$PWD/audiodevice.cpp \
    $$PWD/audiodevicemodel.cpp \
    $$PWD/audiodummy.cpp \
    $$PWD/audioengine.cpp \
    $$PWD/audioengineworkerthread.cpp \
    $$PWD/audiofiledevice.cpp \
    $$PWD/audioport.cpp \
    $$PWD/automatablemodel.cpp \
    $$PWD/clip.cpp \
    $$PWD/datafile.cpp \
    $$PWD/dummyeffect.cpp \
    $$PWD/effect.cpp \
    $$PWD/effectchain.cpp \
    $$PWD/effectcontrols.cpp \
    $$PWD/engine.cpp \
    $$PWD/journallingobject.cpp \
    $$PWD/locklessallocator.cpp \
    $$PWD/locklesslist.cpp \
    $$PWD/metermodel.cpp \
    $$PWD/microtimer.cpp \
    $$PWD/mixer.cpp \
    $$PWD/mixhelpers.cpp \
    $$PWD/outputsettings.cpp \
    $$PWD/playhandle.cpp \
    $$PWD/plugin.cpp \
    $$PWD/portaudiodevice.cpp \
    $$PWD/projectjournal.cpp \
    $$PWD/sampleblock.cpp \
    $$PWD/samplebuffer.cpp \
    $$PWD/sampleclip.cpp \
    $$PWD/sampleframe.cpp \
    $$PWD/sampleplayhandle.cpp \
    $$PWD/sampletrack.cpp \
    $$PWD/serializingobject.cpp \
    $$PWD/sharedobject.cpp \
    $$PWD/song.cpp \
    $$PWD/threadablejob.cpp \
    $$PWD/timepos.cpp \
    $$PWD/track.cpp \
    $$PWD/trackcontainer.cpp \
    $$PWD/visrhelper.cpp \
    $$PWD/fifobuffer.cpp \
    $$PWD/audiofilewave.cpp \
    $$PWD/rendermanager.cpp \
    $$PWD/projectrenderer.cpp \


HEADERS += \
    $$PWD/audio_global.h \
    $$PWD/audiodevice.h \
    $$PWD/audiodevicemodel.h \
    $$PWD/audiodummy.h \
    $$PWD/audioengine.h \
    $$PWD/audioengineworkerthread.h \
    $$PWD/audiofiledevice.h \
    $$PWD/audioport.h \
    $$PWD/automatablemodel.h \
    $$PWD/clip.h \
    $$PWD/datafile.h \
    $$PWD/dummyeffect.h \
    $$PWD/effect.h \
    $$PWD/effectchain.h \
    $$PWD/effectcontrols.h \
    $$PWD/engine.h \
    $$PWD/journallingobject.h \
    $$PWD/locklessallocator.h \
    $$PWD/locklesslist.h \
    $$PWD/metermodel.h \
    $$PWD/microtimer.h \
    $$PWD/mixer.h \
    $$PWD/mixhelpers.h \
    $$PWD/outputsettings.h \
    $$PWD/playhandle.h \
    $$PWD/plugin.h \
    $$PWD/portaudiodevice.h \
    $$PWD/projectjournal.h \
    $$PWD/sampleblock.h \
    $$PWD/samplebuffer.h \
    $$PWD/sampleclip.h \
    $$PWD/sampleframe.h \
    $$PWD/sampleplayhandle.h \
    $$PWD/sampletrack.h \
    $$PWD/serializingobject.h \
    $$PWD/sharedobject.h \
    $$PWD/song.h \
    $$PWD/threadablejob.h \
    $$PWD/timepos.h \
    $$PWD/track.h \
    $$PWD/trackcontainer.h \
    $$PWD/visrhelper.h \
    $$PWD/fifobuffer.h \
    $$PWD/audiofilewave.h \
    $$PWD/rendermanager.h \
    $$PWD/projectrenderer.h \




